pipeline {
    agent any

    stages {
        stage('Pull Code') {
            steps {
                git branch: 'main', url: 'https://github.com/trabnm1313/SDTP.git'
            }
        }
        stage('Download Dependencies') {
            steps {
                dir("frontend"){
                    sh 'yarn install'
                }
            }
        }
        stage('Conponents Testing') {
            steps {
                dir("frontend"){
                    sh 'yarn run components-testing'
                }
            }
        }
        stage('E2E Testing') {
            steps {
                echo "E2E testing mockup"
                publishHTML([allowMissing: false, alwaysLinkToLastBuild: false, keepAll: false, reportDir: 'frontend/cypress/reports', reportFiles: 'report.html', reportName: 'HTML Report', reportTitles: ''])
            }
        }
    }
    post { 
        always { 
            cleanWs()
        }
    }
}