pipeline {
    agent any
    environment{
        SECRET_FILE = credentials('team2-secret')
    }

    stages {
        stage('Pull Code') {
            steps {
                cleanWs()
                git branch: 'main', url: 'https://github.com/trabnm1313/SDTP.git'
            }
        }
        stage('Download Dependencies') {
            steps {
                dir("backend"){
                    sh 'npm install'
                }
            }
        }
        stage('Unit Test') {
            steps {
                dir("backend"){
                    sh 'npm run unit_test'
                    publishHTML([allowMissing: false, alwaysLinkToLastBuild: false, keepAll: false, reportDir: 'backend/reports', reportFiles: 'report.html', reportName: 'HTML Report', reportTitles: ''])
                }
            }
        }
        stage('Component Test') {
            steps {
                dir("backend"){
                    sh 'cp ${SECRET_FILE} key.json'
                    sh 'npm run component_test'
                    sh 'rm key.json'
                }
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploy'
            }
        }
        stage('E2E test') {
            steps {
                echo 'npm e2e_test'
            }
        }
        stage('Notification') {
            steps {
                echo 'Everything is OK'
            }
        }
    }
}
